### ISSUE TITLE
Crashing node-red 2.0.5

### ISSUE THREAD

**Issue by 0rsa** [clausbroch/node-red-contrib-noble-bluetooth#12]
Hi,
Using
node-red 2.0.5
nodejs 14.17.6
When I restart node-red or republish all flows, node-red crashes with this error:
`18 Sep 17:12:06 - [red] Uncaught Exception:
18 Sep 17:12:06 - Error: EALREADY, Operation already in progress
    at Hci.init (/home/flo/nodered/node_modules/@abandonware/noble/lib/hci-socket/hci.js:120:18)
    at Hci.pollIsDevUp (/home/flo/nodered/node_modules/@abandonware/noble/lib/hci-socket/hci.js:135:14)
    at listOnTimeout (internal/timers.js:557:17)
    at processTimers (internal/timers.js:500:7)
17:12:06.043 DRIVER   destroying driver instance...
`

**Comment by WhiteLionATX** [comment]
same for me with 2.06
`18 Oct 21:58:11 - [error] [BLE scanner:1961199c2d5151c8] Error scanning for devices: Error: Could not start scanning, state is poweredOff (not poweredOn)
18 Oct 21:58:27 - [red] Uncaught Exception:
18 Oct 21:58:27 - Error: EALREADY, Operation already in progress
    at Hci.init (/home/pi/.node-red/node_modules/@abandonware/noble/lib/hci-socket/hci.js:120:18)
    at Hci.pollIsDevUp (/home/pi/.node-red/node_modules/@abandonware/noble/lib/hci-socket/hci.js:135:14)
    at ontimeout (timers.js:436:11)
    at tryOnTimeout (timers.js:300:5)
    at listOnTimeout (timers.js:263:5)
    at Timer.processTimers (timers.js:223:10)
noble warning: adapter state unauthorized, please run as root or with sudo
               or see README for information on running without root/sudo:
               https://github.com/sandeepmistry/noble#running-on-linux
18 Oct 21:58:27 - [info] [BLE scanner:1961199c2d5151c8] BLE state: unauthorized
nodered.service: Main process exited, code=exited, status=1/FAILURE
nodered.service: Failed with result 'exit-code'.
nodered.service: Service RestartSec=20s expired, scheduling restart.
nodered.service: Scheduled restart job, restart counter is at 1.
Stopped Node-RED graphical event wiring tool.
Started Node-RED graphical event wiring tool.
18 Oct 21:58:49 - [info]
Welcome to Node-RED
`
